import { describe, it, expect } from 'vitest';
import { MINI_BUNDLE, MINI_CODE_REPOS, NEW_PAGE_TEXT, INVALID_PAGE_TEXT } from '@platform/contracts/testing';
import { planPageChanges, planPublish } from '../src/index.js';

const ctx = { codeRepos: MINI_CODE_REPOS, author: 'Rayan Yousef', message: 'Add combat', date: '2026-09-07' };

describe('planPageChanges', () => {
  it('adds the page, regenerates the folder index, manifest, code map and log', () => {
    const cs = planPageChanges(MINI_BUNDLE, [{ path: 'systems/combat.md', text: NEW_PAGE_TEXT }], ctx);
    expect(Object.keys(cs.writes).sort()).toEqual(['code-maps/acme--game.md', 'log.md', 'manifest.json', 'systems/combat.md', 'systems/index.md']);
    expect(cs.regenerated.sort()).toEqual(['code-maps/acme--game.md', 'log.md', 'manifest.json', 'systems/index.md']);
    expect(cs.writes['log.md']).toContain('## 2026-09-07\n\n* **Add**: [Combat](/systems/combat.md) - Add combat. (by Rayan Yousef)');
    expect(cs.deletes).toEqual([]);
  });
  it('logs Update for an existing page', () => {
    const cs = planPageChanges(MINI_BUNDLE, [{ path: 'systems/inventory.md', text: MINI_BUNDLE['systems/inventory.md']! + '\nMore.\n' }], { ...ctx, message: 'Expand' });
    expect(cs.writes['log.md']).toContain('* **Update**: [Inventory](/systems/inventory.md) - Expand. (by Rayan Yousef)');
    expect(cs.writes['manifest.json']).toBeUndefined();
  });
  it('deletes remove the bullet and the manifest entry', () => {
    const added = planPageChanges(MINI_BUNDLE, [{ path: 'systems/combat.md', text: NEW_PAGE_TEXT }], ctx);
    const files = { ...MINI_BUNDLE, ...added.writes };
    const cs = planPageChanges(files, [{ path: 'systems/combat.md', text: null }], ctx);
    expect(cs.deletes).toEqual(['systems/combat.md']);
    expect(cs.writes['systems/index.md']).not.toContain('combat.md');
    expect(cs.writes['manifest.json']).not.toContain('combat');
  });
  it('throws VALIDATION with problems for an invalid page', () => {
    expect(() => planPageChanges(MINI_BUNDLE, [{ path: 'systems/bad.md', text: INVALID_PAGE_TEXT }], ctx)).toThrow(expect.objectContaining({ code: 'VALIDATION' }));
  });
});

describe('planPublish', () => {
  const sha = 'c'.repeat(40);
  it('snapshots with rewritten refs, writes pins, sidebars and versions.json', () => {
    const plan = planPublish(MINI_BUNDLE, '1.1.0', [], MINI_CODE_REPOS, { 'acme/game': sha }, '2026-09-07T00:00:00Z');
    expect(plan.tag).toBe('docs-v1.1.0');
    expect(plan.writes['versioned_docs/version-1.1.0/systems/inventory.md']).toContain(`/blob/${sha}/Assets/Scripts/Inventory`);
    expect(plan.writes['versioned_docs/version-1.1.0/manifest.json']).toContain(`/blob/${sha}/`);
    expect(plan.writes['versioned_docs/version-1.1.0/code-maps/acme--game.md']).toBeDefined();
    expect(JSON.parse(plan.writes['docs/versions/1.1.0.json']!)).toEqual({ version: '1.1.0', frozenAt: '2026-09-07T00:00:00Z', pins: { 'acme/game': sha }, refs: { 'acme/game': 'main' } });
    expect(JSON.parse(plan.writes['versions.json']!)).toEqual(['1.1.0']);
    expect(JSON.parse(plan.writes['versioned_sidebars/version-1.1.0-sidebars.json']!)).toEqual({ docsSidebar: [{ type: 'autogenerated', dirName: '.' }] });
  });
  it('refuses an existing version with EXISTS', () => {
    expect(() => planPublish(MINI_BUNDLE, '1.0.0', ['1.0.0'], MINI_CODE_REPOS, { 'acme/game': sha }, '2026-09-07T00:00:00Z')).toThrow(expect.objectContaining({ code: 'EXISTS' }));
  });
});
