import { ContentError, type CodeRepoRef, repoKey } from '@platform/contracts';
import { generateBundle, rewriteRefs, type RefRewrite } from '@platform/okf-core';

export interface PublishPlan { writes: Record<string, string>; tag: string; pins: Record<string, string> }

export function planPublish(latest: Record<string, string>, version: string, versionsJson: string[], codeRepos: CodeRepoRef[], pins: Record<string, string>, frozenAt: string): PublishPlan {
  if (!/^\d+\.\d+\.\d+$/.test(version)) throw new ContentError('VALIDATION', `Version must look like 1.2.3, got "${version}"`);
  if (versionsJson.includes(version)) throw new ContentError('EXISTS', `Version ${version} already exists`);
  const rewrites: Record<string, RefRewrite> = {};
  const refs: Record<string, string> = {};
  for (const r of codeRepos) {
    const key = repoKey(r);
    const sha = pins[key];
    if (!sha) throw new ContentError('VALIDATION', `No pin resolved for ${key}`);
    rewrites[key] = { from: r.defaultRef, to: sha };
    refs[key] = r.defaultRef;
  }
  const snapshot: Record<string, string> = {};
  for (const [path, text] of Object.entries(latest)) {
    if (path.startsWith('versions/')) continue;
    snapshot[path] = rewriteRefs(text, rewrites);
  }
  const gen = generateBundle(snapshot, { codeRepos });
  if (gen.problems.length) throw new ContentError('VALIDATION', 'Latest bundle must validate before publishing', gen.problems);
  Object.assign(snapshot, gen.writes);
  const dir = `versioned_docs/version-${version}`;
  const writes: Record<string, string> = {};
  for (const [path, text] of Object.entries(snapshot)) writes[`${dir}/${path}`] = text;
  writes[`docs/versions/${version}.json`] = JSON.stringify({ version, frozenAt, pins, refs }, null, 2) + '\n';
  writes[`versioned_sidebars/version-${version}-sidebars.json`] = JSON.stringify({ docsSidebar: [{ type: 'autogenerated', dirName: '.' }] }, null, 2) + '\n';
  writes['versions.json'] = JSON.stringify([version, ...versionsJson], null, 2) + '\n';
  return { writes, tag: `docs-v${version}`, pins };
}
