name: ToDrive - APK Build and Upload - Android

on:
  workflow_dispatch:
  workflow_call:

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  buildAPK:
    name: Build APK for Android ðŸ–¥ï¸
    runs-on: ubuntu-22.04
    timeout-minutes: 220
    strategy:
      fail-fast: false
    steps:
      - name: Delete huge unnecessary tools folder
        run: rm -rf /opt/hostedtoolcache

      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main # https://github.com/jlumbroso/free-disk-space
        with:
          tool-cache: false

          android: false
          dotnet: false
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: false

      - name: Checkout code
        uses: actions/checkout@v4 # https://github.com/actions/checkout
        with:
         # ref: main
         lfs: true

      - name: Create LFS file list
        run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id

      - name: Restore LFS cache
        uses: actions/cache@v4 # https://github.com/actions/cache
        id: lfs-cache
        with:
          path: .git/lfs
          key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}

      - name: Git LFS Pull
        run: |
          git lfs pull
          git add .
          git reset --hard
      - name: Restore Library cache
        uses: actions/cache@v4 # https://github.com/actions/cache
        with:
          path: SkrewClient/Library
          key: Library-build-Android-APK
          restore-keys: |
            Library-build-Android-APK
            Library-build-
            Library-

      - name: JSON to variables
        uses: rgarcia-phi/json-to-variables@v1.1.0 # https://github.com/rgarcia-phi/json-to-variables
        with:
          filename: 'CloudBuild/VersioningSettings.json'
          prefix: setting

      - uses: game-ci/unity-builder@v4.3.0 # https://github.com/game-ci/unity-builder
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: ./SkrewClient
          targetPlatform: Android
          androidExportType: 'androidPackage'
          buildName: v${{ env.setting_AppVersion }}_bv${{ env.setting_BuildVersionAndroid }}
          versioning : None
          androidVersionCode : 4
          androidKeystorePass: ${{ secrets.ANDROID_KEYSTORE_PASS }}
          androidKeyaliasPass: ${{ secrets.ANDROID_KEYALIAS_PASS }}

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4 # https://github.com/actions/upload-artifact
        with:
          name: Android-APK
          path: build/Android/v${{ env.setting_AppVersion }}_bv${{ env.setting_BuildVersionAndroid }}.apk

  uploadToDrive:
    name: Upload to Google Drive
    runs-on: ubuntu-latest
    needs: buildAPK
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: JSON to variables
        uses: rgarcia-phi/json-to-variables@v1.1.0
        with:
          filename: 'CloudBuild/VersioningSettings.json'
          prefix: setting

      - name: Download the Build Artifact
        uses: actions/download-artifact@v4 # https://github.com/actions/download-artifact
        with:
          name: Android-APK
          path: ./BuildData

      - name: run singleLine
        run: |
            ls -a
            cd BuildData
            ls -a

      - name: Verify the artifact download
        run: ls -l ./BuildData/v${{ env.setting_AppVersion }}_bv${{ env.setting_BuildVersionAndroid }}.apk

      - name: Upload Build to Google Drive
        uses: Jumbo810/Upload_Github_Artifacts_TO_GDrive@v2.3.1 # https://github.com/Jumbo810/Upload_Github_Artifacts_TO_GDrive
        with:
          target: ./BuildData/v${{ env.setting_AppVersion }}_bv${{ env.setting_BuildVersionAndroid }}.apk
          credentials: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_CREDENTIALS }}
          parent_folder_id: ${{ vars.GOOGLE_DRIVE_PARENT_FOLDER_ID }}

  notifyAPK:
    permissions: read-all
    name: Discord Notification for APK Build
    runs-on: ubuntu-latest
    needs:
      - uploadToDrive
    if: ${{ success() || failure() }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: JSON to variables (for build name)
        uses: rgarcia-phi/json-to-variables@v1.1.0
        with:
          filename: 'CloudBuild/VersioningSettings.json'
          prefix: setting

      - name: Notify APK Build
        uses: nobrayner/discord-webhook@v1 # https://github.com/nobrayner/discord-webhook
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          discord-webhook: ${{ secrets.DISCORD_WEBHOOK_SKREW }}
          username: 'Build Notifier'
          include-details: true
          title: 'APK Build and Upload to Google Drive'
          description: 'The APK has been uploaded to Google Drive. Release: v${{ env.setting_AppVersion }}_bv${{ env.setting_BuildVersionAndroid }} | File: v${{ env.setting_AppVersion }}_bv${{ env.setting_BuildVersionAndroid }}.apk'
